FROM node:lts AS build
WORKDIR /usr/src/app
COPY ./pass3-identity/package*.json ./
RUN npm install
COPY ./pass3-identity/. .
RUN npm run build

# Deployment step

FROM nginx as deploy

COPY --from=build /usr/src/app/build/. /usr/share/nginx/html/.

RUN ls -al /usr/share/nginx/html
